image: node-front-runner
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build
  - deploy

build_dev:
  stage: build
  variables:
    TAR_NAME: "nextjs-cm-admin.tar.gz"
    RUNNER_DIR: "/home/itras/apps/campus-management/dev/$CI_PROJECT_NAME"
    DEPL_DIR: "/home/itras/apps/campus-management/dev"
    HOSTER_DIR: "~/campus-management"
    BUILD_PARAM: "nextjs-cm-admin"
  only:
    refs:
      - develop
  script:
    - source ~/.bashrc
    - nvm list | grep "v18.15.0" || nvm install 18.15.0
    - nvm use 18.15.0
    - npm install --legacy-peer-deps
    - npm run build
    - ssh $SSH_USER@$IP_ADDRESS "mkdir -p $RUNNER_DIR"
    - ssh $SSH_USER@$IP_ADDRESS "chmod -R 755 $RUNNER_DIR"
    - cd ..
    - tar -zcf $TAR_NAME $CI_PROJECT_NAME/
    - scp -r $TAR_NAME $SSH_USER@$IP_ADDRESS:$RUNNER_DIR
    - rm $TAR_NAME

deploy_dev:
  stage: deploy
  variables:
    TAR_NAME: "nextjs-cm-admin.tar.gz"
    RUNNER_DIR: "/home/itras/apps/campus-management/dev/$CI_PROJECT_NAME"
    DEPL_DIR: "/home/itras/apps/campus-management/dev"
    HOSTER_DIR: "~/campus-management"
    BUILD_PARAM: "nextjs-cm-admin"
  when: manual
  only:
    refs:
      - develop
  script:
    - ssh $SSH_USER@$IP_ADDRESS "cd $RUNNER_DIR && tar -xzf $TAR_NAME --overwrite && rm $TAR_NAME"
    - ssh $SSH_USER@$IP_ADDRESS "cd $DEPL_DIR && cp .env.local $CI_PROJECT_NAME/$CI_PROJECT_NAME"
    - ssh $SSH_USER@$IP_ADDRESS "cd $DEPL_DIR && docker compose rm -sf campus-management"
    - ssh $SSH_USER@$IP_ADDRESS "cd $DEPL_DIR && docker compose up -d --build campus-management"

build_prod:
  stage: build
  variables:
    TAR_NAME: "nextjs-ic-community.tar.gz"
    RUNNER_DIR: "/home/runner/fs1/$CI_PROJECT_NAME/prod"
    HOSTER_DIR: "/home/itras/www/innovation-campus-admin"
    DEPL_DIR: "/home/itras/apps/ic-community/deployment-ic-community"
    BUILD_PARAM: "nextjs-ic-community"
  only:
    refs:
      - master
  script:
    - source ~/.bashrc
    - nvm use 16.13.2
    - npm install --legacy-peer-deps
    - npm run lint
    - npm run build:prod
    - ssh runner@192.168.2.38 "mkdir -p $RUNNER_DIR"
    - ssh runner@192.168.2.38 "chmod 777 $RUNNER_DIR"
    - ssh runner@192.168.2.38 "rm -rf $RUNNER_DIR/*"
    - tar -zcf $TAR_NAME dist/$CI_PROJECT_NAME/
    - scp -r $TAR_NAME runner@192.168.2.38:$RUNNER_DIR
    - rm $TAR_NAME

deploy_prod:
  stage: deploy
  variables:
    TAR_NAME: "nextjs-ic-community.tar.gz"
    RUNNER_DIR: "/home/runner/fs1/$CI_PROJECT_NAME/prod"
    HOSTER_DIR: "/home/itras/www/innovation-campus-admin"
    DEPL_DIR: "/home/runner/fs1/innovation-campus-admin-docker/prod/deployment"
    BUILD_PARAM: "nextjs-ic-community"
  when: manual
  only:
    refs:
      - master
  script:
    - ssh -p 4826 itras@5.196.174.40 "chmod +x $HOSTER_DIR/fast-deploy.sh"
    - ssh -p 4826 itras@5.196.174.40 "(cd $HOSTER_DIR && ./fast-deploy.sh nextjs-ic-community)"
