version: "3"
services:
  quiz-management:
    container_name: quiz-management
    build: ./
    ports:
      - "21623:3002"
    expose:
      - 21623
    env_file:
      - ./.env.local

networks:
  default:
    external: true
    name: cm_network